//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaConexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class BODEGA
    {
        public BODEGA()
        {
            this.TIENDA = new HashSet<TIENDA>();
        }
    
        public decimal ID_BODEGA { get; set; }
        public string NOMBRE_BODEGA { get; set; }
        public decimal STOCK_PRODUCTO { get; set; }
        public decimal ID_PRODUCTO { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual ICollection<TIENDA> TIENDA { get; set; }
    }
}
