//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaConexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIUDAD
    {
        public CIUDAD()
        {
            this.TIENDA = new HashSet<TIENDA>();
        }
    
        public decimal ID_CIUDAD { get; set; }
        public string NOMBRE_CIUDAD { get; set; }
        public decimal ID_REGION { get; set; }
    
        public virtual REGION REGION { get; set; }
        public virtual ICollection<TIENDA> TIENDA { get; set; }
    }
}
