//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaConexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMA_PAGO
    {
        public FORMA_PAGO()
        {
            this.VENTA = new HashSet<VENTA>();
        }
    
        public decimal ID_FORMAPAGO { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<VENTA> VENTA { get; set; }
    }
}
