//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaConexion
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BODEGA> BODEGA { get; set; }
        public DbSet<BOLETA> BOLETA { get; set; }
        public DbSet<CATEGORIA> CATEGORIA { get; set; }
        public DbSet<CIUDAD> CIUDAD { get; set; }
        public DbSet<FORMA_PAGO> FORMA_PAGO { get; set; }
        public DbSet<MULTIMEDIA> MULTIMEDIA { get; set; }
        public DbSet<OFERTA> OFERTA { get; set; }
        public DbSet<PAIS> PAIS { get; set; }
        public DbSet<PRODUCTO> PRODUCTO { get; set; }
        public DbSet<REGION> REGION { get; set; }
        public DbSet<SUBCATEGORIA> SUBCATEGORIA { get; set; }
        public DbSet<TIENDA> TIENDA { get; set; }
        public DbSet<USER_CLIENTE> USER_CLIENTE { get; set; }
        public DbSet<USER_TIENDA> USER_TIENDA { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<VENTA> VENTA { get; set; }
    }
}
