//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaConexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class MULTIMEDIA
    {
        public MULTIMEDIA()
        {
            this.PRODUCTO = new HashSet<PRODUCTO>();
        }
    
        public decimal ID_MULTIMEDIA { get; set; }
        public string EXTENSION_ARCHIVO { get; set; }
        public byte[] ARCHIVO { get; set; }
    
        public virtual ICollection<PRODUCTO> PRODUCTO { get; set; }
    }
}
