//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaConexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFERTA
    {
        public OFERTA()
        {
            this.VENTA = new HashSet<VENTA>();
        }
    
        public decimal ID_OFERTA { get; set; }
        public decimal PRECIO { get; set; }
        public decimal CONTADOR_VISITA { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public decimal ID_TIENDA { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual TIENDA TIENDA { get; set; }
        public virtual ICollection<VENTA> VENTA { get; set; }
    }
}
