//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaConexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public PRODUCTO()
        {
            this.BODEGA = new HashSet<BODEGA>();
            this.OFERTA = new HashSet<OFERTA>();
        }
    
        public decimal ID_PRODUCTO { get; set; }
        public string NOMBRE_PRODUCTO { get; set; }
        public string MARCA { get; set; }
        public Nullable<System.DateTime> FECHA_VENC { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal VALORACION { get; set; }
        public decimal ID_CATEGORIA { get; set; }
        public decimal ID_MULTIMEDIA { get; set; }
    
        public virtual ICollection<BODEGA> BODEGA { get; set; }
        public virtual CATEGORIA CATEGORIA { get; set; }
        public virtual MULTIMEDIA MULTIMEDIA { get; set; }
        public virtual ICollection<OFERTA> OFERTA { get; set; }
    }
}
