//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaConexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGION
    {
        public REGION()
        {
            this.CIUDAD = new HashSet<CIUDAD>();
        }
    
        public decimal ID_REGION { get; set; }
        public string NOMBRE { get; set; }
        public decimal ID_PAIS { get; set; }
    
        public virtual ICollection<CIUDAD> CIUDAD { get; set; }
        public virtual PAIS PAIS { get; set; }
    }
}
