//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaConexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBCATEGORIA
    {
        public SUBCATEGORIA()
        {
            this.CATEGORIA = new HashSet<CATEGORIA>();
        }
    
        public decimal ID_SUBCATEGORIA { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<CATEGORIA> CATEGORIA { get; set; }
    }
}
