//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaConexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_TIENDA
    {
        public USER_TIENDA()
        {
            this.TIENDA = new HashSet<TIENDA>();
        }
    
        public decimal ID_USERTIENDA { get; set; }
        public string CATGO { get; set; }
        public decimal ID_USUARIO { get; set; }
    
        public virtual ICollection<TIENDA> TIENDA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
