//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaConexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.USER_CLIENTE = new HashSet<USER_CLIENTE>();
            this.USER_TIENDA = new HashSet<USER_TIENDA>();
        }
    
        public decimal ID_USUARIO { get; set; }
        public string NOMBRE { get; set; }
        public string USERNAME { get; set; }
        public string PASSWOARD { get; set; }
        public string TIPO_USUARIO { get; set; }
        public decimal ID_PERSONA { get; set; }
    
        public virtual ICollection<USER_CLIENTE> USER_CLIENTE { get; set; }
        public virtual ICollection<USER_TIENDA> USER_TIENDA { get; set; }
    }
}
