//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaConexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTA
    {
        public VENTA()
        {
            this.BOLETA = new HashSet<BOLETA>();
        }
    
        public decimal ID_VENTA { get; set; }
        public System.DateTime FECHA_VENTA { get; set; }
        public decimal MONTO_TOTAL { get; set; }
        public decimal ID_OFERTA { get; set; }
        public decimal ID_USERCLIENTE { get; set; }
        public decimal ID_TIENDA { get; set; }
        public decimal ID_FORMAPAGO { get; set; }
    
        public virtual ICollection<BOLETA> BOLETA { get; set; }
        public virtual FORMA_PAGO FORMA_PAGO { get; set; }
        public virtual OFERTA OFERTA { get; set; }
        public virtual TIENDA TIENDA { get; set; }
        public virtual USER_CLIENTE USER_CLIENTE { get; set; }
    }
}
